[project]
id = "vvrulvxeaejxhwnafwrq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[functions]
enabled = true

[functions.clarify-Questions-gemini]
verify_jwt = false

[functions.deep-Research-gemini]
verify_jwt = false

[functions.generate-ppt-agent]
verify_jwt = false

[functions.document-ingestion-agent]
verify_jwt = false

[functions.create-ppt-job]
verify_jwt = false

